spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/imagelite
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true